on:
  push:
    branches:
    - main

name: Build and Deploy to Cloud Run
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE: nestjs-graphql
  REGION: asia-northeast1
  IMAGE_URL: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/nestjs-graphql:${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        service_account: nestjs-graphql@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

    # Alternative option - authentication via credentials json
    # - id: 'auth'
    #   uses: 'google-github-actions/auth@v1'
    #   with:
    #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    # Setup gcloud CLI
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - name: Authorize Docker push
      run: gcloud auth configure-docker

    - name: Build and Push Container
      run: |-
        docker build -t $IMAGE_URL .
        docker push $IMAGE_URL
    - name: Deploy to Cloud Run
      run: |-
        gcloud run deploy $SERVICE \
          --project=$PROJECT_ID \
          --region $REGION \
          --image $IMAGE_URL \
          --allow-unauthenticated
          --platform "managed" \
          --quiet